const suits=[["♠","black"],["♥","red"],["♦","red"],["♣","black"]],ranks=[["2",2],["3",3],["4",4],["5",5],["6",6],["7",7],["8",8],["9",9],["10",10],["J",11],["Q",12],["K",13],["A",14]];
let deck=[],hand=[],selected=[],round=1,target=300,chips=0,mult=0,money=4,discards=3,jokers=[],gameOver=false;
const jokerPool=[{name:"🌙 月蝕小丑",desc:"每打出一對：+15 Mult",pair:()=>15},{name:"🔥 流星小丑",desc:"每張紅色牌：+8 Chips",red:()=>8},{name:"🎩 魔術帽",desc:"順子額外 +60 Chips",straight:()=>60},{name:"🍀 幸運四葉",desc:"三條或以上：+2 Mult",three:()=>2}];
function $(id){return document.getElementById(id)}
function makeDeck(){deck=[];for(const [s,c] of suits)for(const [r,v] of ranks)deck.push({suit:s,color:c,rank:r,value:v});deck.sort(()=>Math.random()-.5)}
function draw(n=8){while(hand.length<n&&deck.length)hand.push(deck.pop())}
function render(){ $("round").textContent=round;$("target").textContent=target;$("chips").textContent=chips;$("mult").textContent=mult;$("money").textContent=money;$("discards").textContent=discards;
$("hand").innerHTML=hand.map((c,i)=>'<div class="card '+c.color+(selected.includes(i)?' selected':'')+'" onclick="toggle('+i+')"><div class="rank">'+c.rank+'</div><div class="suit">'+c.suit+'</div></div>').join("");
$("jokers").innerHTML=jokers.length?jokers.map(j=>'<div class="joker"><strong>'+j.name+'</strong><div>'+j.desc+'</div></div>').join(""):'<div class="joker"><small>目前沒有小丑牌。去商店找找吧！</small></div>';
$("play").disabled=selected.length===0||selected.length>5||gameOver;$("discard").disabled=selected.length===0||selected.length>5||discards<=0||gameOver}
function toggle(i){if(gameOver)return;selected.includes(i)?selected=selected.filter(x=>x!==i):(selected.length<5&&selected.push(i));render()}
function evaluate(cards){const vals=cards.map(c=>c.value).sort((a,b)=>a-b),counts={};vals.forEach(v=>counts[v]=(counts[v]||0)+1);let flush=cards.length>=5&&cards.every(c=>c.suit===cards[0].suit);let uniq=[...new Set(vals)];let straight=uniq.length===5&&(uniq[4]-uniq[0]===4||JSON.stringify(uniq)==='[2,3,4,5,14]');
let groups=Object.values(counts).sort((a,b)=>b-a);if(straight&&flush)return["同花順",100,8,"straightflush"];if(groups[0]===4)return["四條",80,7,"four"];if(groups[0]===3&&groups[1]===2)return["葫蘆",70,6,"three"];if(flush)return["同花",60,5,"flush"];if(straight)return["順子",50,4,"straight"];if(groups[0]===3)return["三條",40,3,"three"];if(groups[0]===2&&groups[1]===2)return["兩對",30,2,"pair"];if(groups[0]===2)return["一對",20,1,"pair"];return["高牌",5,1,"high"]}
function play(){if(!selected.length||selected.length>5||gameOver)return;const cards=selected.map(i=>hand[i]),e=evaluate(cards);let c=e[1],m=e[2];if(e[3]==="pair")jokers.forEach(j=>{if(j.pair)m+=j.pair()});if(jokers.some(j=>j.red))c+=cards.filter(x=>x.color==="red").length*8;if(e[3]==="straight")jokers.forEach(j=>{if(j.straight)c+=j.straight()});if(["three","four"].includes(e[3]))jokers.forEach(j=>{if(j.three)m+=j.three()});chips=c;mult=m;let score=chips*mult;money+=Math.max(1,Math.floor(score/100));$("message").textContent=e[0]+"！ "+chips+" × "+mult+" = "+score+" 分";hand=hand.filter((_,i)=>!selected.includes(i));selected=[];draw();render();if(score>=target)win();else if(hand.length<5)lose()}
function discard(){if(!selected.length||discards<=0||gameOver)return;hand=hand.filter((_,i)=>!selected.includes(i));selected=[];discards--;draw();$("message").textContent="棄牌了，再組一手看看！";render()}
function win(){gameOver=true;$("message").textContent="🎉 過關！你達成 "+target+" 分，可以進商店。";$("shop").classList.remove("hidden");setupShop();render()}
function lose(){gameOver=true;$("message").textContent="💀 牌組耗盡，挑戰失敗。按「重新開始」再來一次！";render()}
function setupShop(){const choices=[...jokerPool].sort(()=>Math.random()-.5).slice(0,3);$("shopCards").innerHTML=choices.map((j,i)=>'<div class="shopItem"><h3>'+j.name+'</h3><p>'+j.desc+'</p><button onclick="buy('+i+')" '+(money<3?'disabled':'')+'>購買 3 🪙</button></div>').join("");window.shopChoices=choices}
function buy(i){if(money<3)return;money-=3;jokers.push(shopChoices[i]);$("message").textContent="獲得 "+shopChoices[i].name+"！";setupShop();render()}
function nextRound(){round++;target=Math.floor(target*1.65);money+=2;discards=3;gameOver=false;$("shop").classList.add("hidden");chips=0;mult=0;makeDeck();hand=[];draw();$("message").textContent="第 "+round+" 回合：目標 "+target+" 分。";render()}
function restart(){round=1;target=300;money=4;discards=3;jokers=[];gameOver=false;chips=0;mult=0;selected=[];makeDeck();hand=[];draw();$("shop").classList.add("hidden");$("message").textContent="選最多 5 張牌，然後出牌！";render()}
$("play").onclick=play;$("discard").onclick=discard;$("next").onclick=nextRound;$("restart").onclick=restart;restart();